#ifndef _SYSTEM_ARCH_PPC64_ARCH_COMMPAGE_DEFS_H
#define _SYSTEM_ARCH_PPC64_ARCH_COMMPAGE_DEFS_H

#include <commpage_defs.h>

#define COMMPAGE_ENTRY_PPC64_THREAD_EXIT (COMMPAGE_ENTRY_FIRST_ARCH_SPECIFIC + 0)
#define COMMPAGE_ENTRY_PPC64_SIGNAL_HANDLER (COMMPAGE_ENTRY_FIRST_ARCH_SPECIFIC + 1)

#endif
